config/routes.rb
Rails.application.routes.draw do
	root 'kittens#index'
	resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
	def index
		@kittens = Kitten.all

		respond_to do |format|
			format.html
			format.json { render json: @kittens }
		end
	end

	def new
		@kitten = Kitten.new
	end

	def create
		@kitten = Kitten.new(kitten_params)
		if @kitten.save
			flash[:sucess] = "Congrats, you added a kitten to the list!"
			redirect_to @kitten
		else
			render :new
		end
	end

	def show
		@kitten = Kitten.find(params[:id])

		respond_to do |format|
			format.html
			format.json { render json: @kitten }
		end
	end

	def edit
		@kitten = Kitten.find(params[:id])
	end

	def update
		@kitten = Kitten.find(params[:id])
		if @kitten.update_attributes(kitten_params)
			flash[:sucess] = "Purr purr updated, good job you kitten lover!"
			redirect_to @kitten
		else
			render :edit
		end
	end

	def destroy
		Kitten.find(params[:id]).destroy
		flash[:sucess] = "Kitten dead...good job you fucking prick. Get outta here!"
		redirect_to root_url
	end

	private
		def kitten_params
			params.require(:kitten).permit(:name, :age, :cuteness, :softness)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for(@kitten) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<br>
	<%= f.label :name %>
	<%= f.text_field :name, placeholder: "Name" %>
	<br>
	<%= f.label :age %>
	<%= f.number_field :age %>
	<br>
	<%= f.label :cuteness %>
	<%= f.number_field :cuteness, in: 1..10 %>
	<br>
	<%= f.label :softness %>
	<%= f.number_field :softness, in: 1..10 %>
	<br>
	<%= f.submit yield(:button_text) %>
<% end %>

app/views/kittens/_kitten.html.erb
<p> Name: <strong><%= kitten.name %></strong> Age:	<%= kitten.age %> </p>
<p> Cuteness:	<%= kitten.cuteness %> Softness:	<%= kitten.softness %> </p>
<%= link_to "Delete", kitten, method: :delete,
															 data: { confirm: "Are you sure" } %>

app/views/kittens/edit.html.erb
<% provide(:button_text, "Save changes") %>
<h1> Update Kitten Information </h1>

<%= render 'form' %>

<%= link_to "Delete", @kitten, method: :delete,
															 data: { confirm: "Are you sure" } %>

app/views/kittens/index.html.erb
<h1> All Kittens </h1>

<%= render @kittens %>

app/views/kittens/new.html.erb
<% provide(:button_text, "Create kitten") %>
<h1> Kitten information </h1>

<%= render 'form' %>

app/views/kittens/show.html.erb
<h1> Kitten Information </h1>

<%= render @kitten %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <% unless flash.empty? %>
    	<hr>
  	<% end  %>

  	<%= link_to "All Kittens", root_url %>
  	<%= link_to "New Kitten", new_kitten_path %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>